### ISSUE TITLE
[ROADMAP] Specification Version 2.0 // UI5 CLI 2.0

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-tooling#204]
This is a list of possible changes that might be implemented with UI5 CLI 2.0. It is not final. Feedback is appreciated.

**Current master branches of all UI5 Tooling repositories (except [UI5 Tooling](https://github.com/SAP/ui5-tooling/pull/214)) reflect v2.0 development.**

## Specification Version 2.0

`specVersion: '2.0'`

### Breaking Changes

- [x] **Schema validation of ui5.yaml:** UI5 Project will error out for unrecognized fields or wrong values (https://github.com/SAP/ui5-project/pull/274)
- [x] **Require namespace for application and library projects:** UI5 Project must be able to determine the projects namespace. E.g. through the manifest.json or .library file (https://github.com/SAP/ui5-builder/pull/430/files)
    - A manual configuration in the ui5.yaml is not allowed. This is to make sure that UI5 runtime also has access to it
- [x] By default, `.properties` files are assumed to be `UTF-8` encoded instead of `ISO-8859-1` ([documentation](https://sap.github.io/ui5-tooling/pages/Builder/#theme-library))

## Features
- [ ] (possibly 3.0) *Going forward, there are separate Specification Versions for Extensions and Projects as outlined here: https://github.com/SAP/ui5-project/issues/167*
- [x] New `metadata` attributes `deprecated` ~and `restricted`~ will display warnings when such a project is used as a direct dependency (https://github.com/SAP/ui5-project/pull/268)

## UI5 CLI 2.0

`@ui5/cli@2.0`

### Breaking changes

- [x] **Drop support for Node.js Version <10 ~(or possibly <12)~:** Node.js 8 and 9 are [EOL](https://github.com/nodejs/Release#end-of-life-releases)
    - [Various](https://github.com/npm/node-semver/commit/d61f828e64260a0a097f26210f5500e91a621828) [dependencies](https://github.com/sindresorhus/globby/commit/4a471af4ca368b27641a3aa7f88f7083ea428db4) require Node.js 10 now
- [x] _**Remove export of all sub-modules from each UI5-modules `index.js`:** Synchronous require of unneeded modules is bad for performance. [Example](https://github.com/SAP/ui5-builder/blob/ab6562ff67aeabb8f6920e220cee0b2b9a4303cd/index.js#L5)_
    - ~Alternative to be discussed~~
    - ➡️ Implemented lazy requires in all index.js
- [x] *Remove synchronous export of all tasks in UI5 Builder `taskRepository`*
- [x] Remove deprecated `useNamespaces` parameter from UI5 Project [`resourceFactory.createCollectionsForTree`](https://sap.github.io/ui5-tooling/api/module-@ui5_fs.resourceFactory.html#.createCollectionsForTree) API (https://github.com/SAP/ui5-fs/pull/223)
- [x] [Bump Yargs](https://github.com/SAP/ui5-cli/issues/266)

### Features

- [x] Support for Specification Version 2.0 (https://github.com/SAP/ui5-project/pull/277)
- [x] UI5 installer (https://github.com/SAP/ui5-project/pull/265)
    - Required for consuming SAPUI5 libraries from npm. Blog post coming soon!
- [x] builder: [[FEATURE] buildThemes: Add filtering for available themes](https://github.com/SAP/ui5-builder/pull/419)
- [x] server: [[FEATURE] Add test runner middleware](https://github.com/SAP/ui5-server/pull/293)

### Bug Fixes
- [x] UI5 Server: [Node 12.8.0 and --h2 option leads to crash](https://github.com/SAP/ui5-server/issues/224)

**Comment by bd82** [comment]
I believe Node.js 10 support should be kept until 04/2021 to align with Node.js LTS schedule.
- https://nodejs.org/en/about/releases/

**Comment by cschuff** [comment]
Would love to see schema validation and json schemas for ui5.yaml. That could as well lead to more tooling support coming from the community :)

**Comment by RandomByte** [comment]
Everything that is ticked off has bee released with **UI5 CLI v2.0.1** 🎉 

**Resources:**
- [Migration Guide for UI5 Tooling v2](https://sap.github.io/ui5-tooling/updates/migrate-v2/)
- **SAPUI5 Consumption**
    - [Announcement Blog Post](https://blogs.sap.com/2020/04/01/introducing-ui5-tooling-for-sapui5-projects/)
    - [Technical Blog Post](https://blogs.sap.com/2020/04/01/ui5ers-buzz-49-the-ui5-tooling-and-sapui5-the-next-step/)
    - [Documentation](https://sap.github.io/ui5-tooling/pages/SAPUI5/)
- [Updated Getting Started](http://localhost:8000/pages/GettingStarted/)
- [openui5-sample-app](https://github.com/SAP/openui5-sample-app) will be updated soon
