### ISSUE TITLE
Custom Task is not called in the build process

### ISSUE THREAD

**Issue by FWidm** [SAP/ui5-tooling#292]
Hi I've seen question SAP/ui5-tooling#291 and was pleased to see that ui5 tooling allows custom tasks. I went ahead and tried to write a small extension for the openui5 sample app. Are custom tasks only available for libraries or does the type of the application not matter for this (as i suspected)?

## Expected Behavior
The custom task is executed or at least should be called.

## Current Behavior
The custom task is not executed that has been defined.

```
info builder:builder Building project openui5-sample-app not including dependencies...
info builder:builder 🛠  (1/1) Building project openui5-sample-app
info builder:builder application openui5-sample-app 🔨 (1/7) Running task replaceCopyright...
info builder:builder application openui5-sample-app 🔨 (2/7) Running task replaceVersion...
info builder:builder application openui5-sample-app 🔨 (3/7) Running task generateFlexChangesBundle...
info builder:processors:bundlers:flexChangesBundler Changes collected. Number of changes: 0
info builder:builder application openui5-sample-app 🔨 (4/7) Running task generateComponentPreload...
info builder:builder application openui5-sample-app 🔨 (5/7) Running task createDebugFiles...
info builder:builder application openui5-sample-app 🔨 (6/7) Running task uglify...
info builder:builder application openui5-sample-app 🔨 (7/7) Running task generateVersionInfo...
info builder:builder Build succeeded in 3.54 s
```

## Steps to reproduce the issue
I was looking for the same thing but could not get a custom job according to your small tutorial to work on the sample app project:

here is what i tried:
- clone a new copy of the project https://github.com/SAP/openui5-sample-app
- expand the ui5yaml
```yaml
specVersion: "1.0"
kind: project
type: application
metadata:
  name: openui5-sample-app
builder:
	customTasks:
		- name: demoTask
		  afterTask: uglify
		  configuration:
			  color: blue
---
# Task extension as part of your project
specVersion: "1.0"
kind: extension
type: task
metadata:
  name: demoTask
task:
  path: tasks/demoTask.js
```
- create folder `tasks` in the project root on the same level as webapp
- create the demo task in the `task` folder
```js
module.exports = async function({workspace, dependencies, options}) {
	console.log(workspace,dependencies,options)
};
```

## Context
- UI5 CLI: 1.4.0
- latest copy of the openui5 demo app

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

Thanks for your time!
