### ISSUE TITLE
[ROADMAP] Specification Version 3.0 // UI5 Tooling 3.0

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-tooling#506]
## UI5 Tooling 3.0

UI5 Tooling 3.0 is the official, feature complete successor of [grunt-openui5](https://github.com/SAP/grunt-openui5/). This allows us to deprecate grunt-openui5.

**🔮 Update:** Since October 2022, UI5 Tooling 3.0 development is done in the `main` branches in the UI5 Tooling repositories. The UI5 Tooling 2.0 sources can be found in the `v2` branches in the UI5 Tooling repositories.
**Pre-releases are available** via npm and tagged as `next`. For example: `npm install @ui5/cli@next`. See also: https://sap.github.io/ui5-tooling/v3/updates/migrate-v3/

### Breaking changes

- [x] Drop support for **Node.js Version < 16**
    - Do not support Node 14, due to lack of features and upcoming end-of-life in April 2023
    - Do not support Node 15 as it is [already EOL](https://github.com/nodejs/Release#end-of-life-releases)
    - Support Node 16.18.0, the latest maintenance release for 16.x as of October 2022
    - Do not support Node 17 as it is [already EOL](https://github.com/nodejs/Release#end-of-life-releases)
    - Support Node 18.0.0 and all later versions
    - Upgrade npm lockfiles to [version 2](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion)
- [x] Require projects to use **`specVersion` 2.0 or later**
    - This would allow us to fully rely on the [schema validation](https://sap.github.io/ui5-tooling/api/module-@ui5_project.validation.validator.html) and to remove additional validation code from various places
    - This also eases the implementation of RFC 0009
    - We attempt to upgrade old specVersions automatically. If a specVersion below 2.0 (i.e. 1.1, 1.0, 0.1) project passes the validation for specVersion 2, it is used as-is.
- [x] Implement **[RFC] 0009 UI5 Project Refactoring** (https://github.com/SAP/ui5-tooling/pull/501)
    - Depending on how far we get it, this might incompatibly change the signatures of many UI5 Tooling modules
- [x] Deprecate, remove or noop the [manifestBundler task](https://sap.github.io/ui5-tooling/api/module-@ui5_builder.processors.html#.manifestBundler) (see https://github.com/SAP/ui5-builder/pull/838)
- [x] ui5-builder: jsdoc exit code 1 should fail the build (see https://github.com/SAP/ui5-builder/pull/617#pullrequestreview-684499820, https://github.com/SAP/ui5-builder/pull/845)
- [x] ui5-fs: Clone resource on read (https://github.com/SAP/ui5-fs/pull/448)
- [x] ui5-fs: Clone resource on write (https://github.com/SAP/ui5-fs/pull/448)
- [x] ui5-server: Remove "/proxy" endpoint (https://github.com/SAP/ui5-server/pull/550)

### Features

- [x] **Source Maps** for bundles (https://github.com/SAP/ui5-tooling/issues/472)
    - ~Maybe already in a 2.x release, depending on compatibility of the changes~
- [x] ~Option to **only build certain dependencies** (https://github.com/SAP/ui5-tooling/issues/494)~ (**Already released with [v2.12.0](https://github.com/SAP/ui5-cli/releases/tag/v2.12.0))**
- [x] Allow theme build and version info generation for **libraries without `.library`** file (https://github.com/SAP/ui5-builder/pull/676) **(Already releases with [v2.14.2](https://github.com/SAP/ui5-cli/releases/tag/v2.14.2))**
- [x] **[RFC] 0006 Local Dependency Resolution** (https://github.com/SAP/ui5-tooling/pull/157). Realization will come with 3.X.
- [x] Upgrade Espree to support ES2021 syntax features (see https://github.com/SAP/ui5-builder/pull/615 / https://github.com/SAP/ui5-builder/pull/692, meanwhile even https://github.com/SAP/ui5-builder/pull/848)

## Specification Version 3.0

- [x] SpecVersion Upgrade: https://github.com/SAP/ui5-project/pull/522

### Features

- [x] Enhance custom task helper **`taskUtil`** as well as middleware helper **`middlewareUtil`**:
    - Allow access to **Projects and Project Graph API** from RFC 0009
        - Via Projects, access to metadata (like the project version) as well as root resources (like `package.json`) would be possible while still using the ui5-fs abstraction layer (https://github.com/SAP/ui5-tooling/issues/360)
    - Pass a ui5-logger **`log` instance** with the name of the extension for its use
    - Allow resource creation via `createResource()` or similar
    - **Concept work done with:** https://github.com/SAP/ui5-tooling/pull/664
    - **Implementation done with:** https://github.com/SAP/ui5-project/pull/514 and https://github.com/SAP/ui5-server/pull/547
- [x] bundleOptions changes (https://github.com/SAP/ui5-tooling/pull/707). See https://sap.github.io/ui5-tooling/pages/Configuration/#properties
  - New option 'sourceMap', defaults to `true` (see https://github.com/SAP/ui5-builder/pull/695)
  - Default of option 'optimize' changed to `true` (API change is done via https://github.com/SAP/ui5-builder/pull/685)

**Comment by RandomByte** [comment]
Thank you for your input Mike! That part of the roadmap was slightly outdated, so I updated it with our latest decisions:

> - [x] Drop support for **Node.js Version < 16**
>     - Do not support Node 14, due to lack of features and upcoming end-of-life in April 2023
>    - Do not support Node 15 as it is [already EOL](https://github.com/nodejs/Release#end-of-life-releases)
>    - Support Node 16.18.0, the latest maintenance release for 16.x as of October 2022
>    - Do not support Node 17 as it is [already EOL](https://github.com/nodejs/Release#end-of-life-releases)
>    - Support Node 18.0.0 and all later versions
>    - Upgrade npm lockfiles to [version 2](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion)

We think this could be a good balance. While Node 16 will be EOL in September 2023, Node 18 was only released earlier this year and might not have the same adoption yet. By requiring a recent patch-level for Node 16 though, we have an almost identical set of features available: https://node.green/

Nevertheless, more time has past now. So we'll pick up your input and discuss it in the team 👍  Thanks!

**Comment by RandomByte** [comment]
We are currently in the process of publishing a first **Release Candidate** for UI5 Tooling v3.

@pubmikeb We decided to actually go with Node v16.16 as the minimum required version. The main reason for this is that SAP Business Application Studio currently uses that version. Based on the information we received, it will remain on that version for the immediate future. We might increase the requirement in the final v3 release based on the situation with BAS.

**Comment by RandomByte** [comment]
We are currently in the process of publishing a first **Release Candidate** for UI5 Tooling v3.

As of the latest discussions, we stick to a minimum Node.js requirement of version 16.18.0, which contains the necessary support for chaining loaders (https://nodejs.org/api/esm.html#loaders), which is required by our test setup.

Unfortunately, SAP Business Application Studio currently uses Node v16.16.0. This means that the latest UI5 Tooling v3 pre-releases can not be used in this environment. We are already in contact with the responsible team and hope to resolve this before the final release of UI5 Tooling v3. Based on the outcome of that discussion, we might even lift the final Node.js version requirement.

**Comment by flovogt** [comment]
Implemented with https://github.com/SAP/ui5-cli/releases/tag/v3.0.0
