### ISSUE TITLE
[ROADMAP] UI5 Tooling 4.0 / Specification Version 4.0

### ISSUE THREAD

**Issue by flovogt** [SAP/ui5-tooling#701]
### Breaking changes
- [x] ui5-builder: Remove bundle option `usePredefineCalls` (CPOUI5FOUNDATION-760)
    - https://github.com/SAP/ui5-builder/pull/1021
    - https://github.com/SAP/ui5-tooling/pull/957 
- [x] ui5-builder: New option “async“ for builder.bundles.bundleDefinition.section (CPOUI5FOUNDATION-789)
    - https://github.com/SAP/ui5-builder/pull/1020
- [x] ui5-project: Set default workspaceName to "default" for API usage (https://github.com/SAP/ui5-project/pull/586/) (CPOUI5FOUNDATION-802)
    - https://github.com/SAP/ui5-project/pull/706
- [x] ui5-project: Rename `ui5HomeDir` to `ui5DataDir` also in APIs (CPOUI5FOUNDATION-802)
    - https://github.com/SAP/ui5-project/pull/707
    - https://github.com/SAP/ui5-cli/pull/687
- [x] ui5-fs: Remove non-public `DuplexCollection#byGlobSource` API (CPOUI5FOUNDATION-802)
    - https://github.com/SAP/ui5-fs/pull/552
- [x] ui5-builder: Task API "namespace" option got renamed to "projectNamespace" (CPOUI5FOUNDATION-802)
   - https://github.com/SAP/ui5-builder/pull/995
- [x] all modules: Occurrences of native `console` should be re-considered to use `stderr` instead of `stdout`
   - https://github.com/SAP/ui5-server/pull/643
   - https://github.com/SAP/ui5-cli/pull/686
- [x] all modules: Node version support `^20.11.0 || >=21.2.0` (CPOUI5FOUNDATION-800, https://github.com/SAP/ui5-tooling/pull/928)
- [x] all modules: NPM version support `>= 10` (CPOUI5FOUNDATION-800, https://github.com/SAP/ui5-tooling/pull/928)

### Features
- [x] https://github.com/SAP/ui5-builder/pull/957

### Dependencies
- CPOUI5FOUNDATION-801
  - [x] ui5-logger: Upgrade breaking [(dev-)dependencies](https://github.com/SAP/ui5-logger/milestone/1)
  - [x] ui5-fs: Upgrade breaking [(dev-)dependencies](https://github.com/SAP/ui5-fs/milestone/1)
  - [x] ui5-builder: Upgrade breaking [(dev-)dependencies](https://github.com/SAP/ui5-builder/milestone/1)
  - [x] ui5-project: Upgrade breaking [(dev-)dependencies](https://github.com/SAP/ui5-project/milestone/1)
  - [x] ui5-server: Upgrade breaking [(dev-)dependencies](https://github.com/SAP/ui5-server/milestone/1)
  - [x] ui5-cli: Upgrade breaking [(dev-)dependencies](https://github.com/SAP/ui5-cli/milestone/2)

### Breaking changes
- [x] Removal of bundle option `usePredefineCalls` (CPOUI5FOUNDATION-760)
- [x] New option “async“ for builder.bundles.bundleDefinition.section. Only applicable if mode = “require”. Default value “true” (CPOUI5FOUNDATION-760)

**Comment by mauriciolauffer** [comment]
Regarding `deployment-task`, pls don't!
https://github.com/SAP/ui5-tooling/issues/490#issuecomment-1515640145

**Comment by flovogt** [comment]
UI5 Tooling Version 4 is officially released https://github.com/SAP/ui5-cli/releases/tag/v4.0.0.
