### ISSUE TITLE
[Roadmap] Production ready UI5 CLI

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-tooling#92]
## Goals
- All [UI5 Tooling modules](https://github.com/SAP/ui5-tooling#modules) shall drop the "This is an alpha release" disclaimers
- The [UI5 CLI](https://github.com/SAP/ui5-cli) shall be released for productive use

## TODO
- [x] Increase test coverage of all modules to at least 80%
	-   Module | Coverage Status | Processor | PR
		--- | --- | --- | ---
		[ui5-cli](https://github.com/SAP/ui5-cli) | [![Coverage Status](https://coveralls.io/repos/github/SAP/ui5-cli/badge.svg?branch=master)](https://coveralls.io/github/SAP/ui5-cli)| @romaniam | ~https://github.com/SAP/ui5-cli/pull/91~
		[ui5-builder](https://github.com/SAP/ui5-builder) | [![Coverage Status](https://coveralls.io/repos/github/SAP/ui5-builder/badge.svg?branch=master)](https://coveralls.io/github/SAP/ui5-builder) | @tobiasso85 | ~https://github.com/SAP/ui5-builder/pull/100~ and ~https://github.com/SAP/ui5-builder/pull/120~
		[ui5-server](https://github.com/SAP/ui5-server) | [![Coverage Status](https://coveralls.io/repos/github/SAP/ui5-server/badge.svg?branch=master)](https://coveralls.io/github/SAP/ui5-server)| @svbender | ~https://github.com/SAP/ui5-server/pull/88~
		[ui5-fs](https://github.com/SAP/ui5-fs) | [![Coverage Status](https://coveralls.io/repos/github/SAP/ui5-fs/badge.svg?branch=master)](https://coveralls.io/github/SAP/ui5-fs)| @domianer | ~https://github.com/SAP/ui5-fs/pull/56~
		[ui5-project](https://github.com/SAP/ui5-project) | [![Coverage Status](https://coveralls.io/repos/github/SAP/ui5-project/badge.svg?branch=master)](https://coveralls.io/github/SAP/ui5-project) | @romaniam | ~https://github.com/SAP/ui5-project/pull/75~
		[ui5-logger](https://github.com/SAP/ui5-logger) | `--no tests--`
- [x] Improve usage documentation
- [x] Fix JSDoc
    - Mark all private functions/modules as private
    - Refactoring
    - ✅➡️ Done with:
        - ~https://github.com/SAP/ui5-tooling/pull/113~
        - ~https://github.com/SAP/ui5-cli/pull/109~
        - ~https://github.com/SAP/ui5-project/pull/92~
        - ~https://github.com/SAP/ui5-server/pull/103~
        - ~https://github.com/SAP/ui5-fs/pull/66~
        - ~https://github.com/SAP/ui5-logger/pull/53~
        - ~https://github.com/SAP/ui5-builder/pull/135~
- [x] Drop alpha-disclaimers
    - ~https://github.com/SAP/ui5-logger/pull/55~
    - ~https://github.com/SAP/ui5-fs/pull/70~
    - ~https://github.com/SAP/ui5-builder/pull/140~
    - ~https://github.com/SAP/ui5-project/pull/97~
    - ~https://github.com/SAP/ui5-server/pull/105~
    - ~https://github.com/SAP/ui5-cli/pull/113~
    - ~https://github.com/SAP/ui5-tooling/pull/117~
- [x] Remove internal changes from changelog
    - ~https://github.com/SAP/ui5-tooling/pull/115~
    - ~https://github.com/SAP/ui5-fs/pull/68~
    - ~https://github.com/SAP/ui5-builder/pull/138~
    - ~https://github.com/SAP/ui5-project/pull/94~
    - ~https://github.com/SAP/ui5-server/pull/104~
    - ~https://github.com/SAP/ui5-cli/pull/110~
    - ~https://github.com/SAP/ui5-logger/pull/54~
- [x] Add [specification version](https://github.com/SAP/ui5-project/blob/master/docs/Configuration.md#specification-versions) "1.0"
    - ~https://github.com/SAP/ui5-project/pull/95~
    - ~https://github.com/SAP/ui5-cli/pull/111~
- [x] Migration Guide: ~https://github.com/SAP/ui5-tooling/pull/116~
- [ ] Release 1.0.0 of all modules

### Open issues
- [x] npm translator cannot handle cyclic dependencies: https://github.com/SAP/ui5-project/issues/50

### Breaking changes
- https://github.com/SAP/ui5-builder/pull/137
- https://github.com/SAP/ui5-project/pull/96
- https://github.com/SAP/ui5-fs/pull/69

**Comment by RandomByte** [comment]
**All done** 🎉 

Announcement: https://twitter.com/matthiaso/status/1083299521352867847
