### ISSUE TITLE
[ROADMAP] UI5 Tooling 5.0 / Specification Version 5.0

### ISSUE THREAD

**Issue by flovogt** [SAP/ui5-tooling#976]
This is a draft, likely to contain more topics than we will actually be able to work on. We appreciate your feedback.

### Breaking changes

- [ ] ui5-builder: Remove `XMLCompositeAnalyzer.js`. `XMLComposite` controls were deprecated with UI5 1.88.0
    - Note long-term support of older UI5 releases which still make use of this. Maybe make this an opt-in option in ui5.yaml?
- [ ] ui5-builder: Relocate `generateJSDoc` to thirdparty module (JIRA: CPOUI5FOUNDATION-593)
- [ ] ui5-builder: Task API changes (minify / buildThemes) in context of [Task Workers RFC](https://github.com/SAP/ui5-tooling/pull/897) (CPOUI5FOUNDATION-700)
- [ ] ui5-server: Remove or deprecate `testRunner` middleware (required resources are part of the npm packages since UI5 1.115)
- [ ] ui5-project: Limit execution of generateManifest task to framework libraries?

### Features

- [ ] New type **`component`** (https://github.com/SAP/ui5-tooling/issues/45)
- [ ] **CDN proxy or adapter** as an alternative to downloading UI5 dependencies in environments with slow I/O
    - Possible a server-only setting or CLI flag
    - Would also pose a workaround for https://github.com/SAP/ui5-tooling/issues/265
- [ ] New extension **`deployment-task`** *(name to be decided)* (https://github.com/SAP/ui5-tooling/issues/490); with corresponding enhancements in specVersion
- [ ] New project type **`project-expansion`** *(name to be decided)* which allows to add resources from a different module to an existing project (https://github.com/SAP/ui5-tooling/issues/500)
    - For example the resources of a polyfill module will then become part of an application project's resources (i.e. included in preloads and with the same flattening on build/serve); with corresponding enhancements in specVersion
 - [ ] ui5-fs: Add an Adapter to handle archives, e.g. `.zip` / `.jar` (https://github.com/SAP/ui5-fs/pull/454)  

### Breaking changes
- [ ] Breaking change: **Require a `manifest.json`** for libraries
